Repository retaildevcrews/helium-typescript, pull requests merged in 2020-03, with the labels that each got.

#77 remove reference to azure Dev Ops and Azure Pipelines
  README.md
Labels: Documentation, Node, Pri1, size: S

#82 Handle Key Vault name and authtype as command line args
  README.md
  src/config/config.ts
  src/config/constants.ts
  src/secrets/keyvaultprovider.ts
  src/server.ts
  src/utilities/commandLineUtilities.ts
Labels: Node

#84 Update helium-typescript swagger docs
  Dockerfile
  Dockerfile-Dev
  src/server.ts
  src/swagger-html.ts
  swagger/swagger.json
Labels: Node

#83 Update helium-typescript to use async/await pattern
  src/db/cosmosdbprovider.ts
  src/secrets/keyvaultprovider.ts
Labels: Node

#85 Updating version to 0.0.6 for M6
  package.json
  src/utilities/versionUtilities.ts
  swagger/swagger.json
Labels: Node

#97 TSLint->ESLint Conversion and Formatting changes
  .eslintrc.json
  jest.config.js
  package-lock.json
  package.json
  src/app/controllers/ActorController.ts
  src/app/controllers/FeaturedController.ts
  src/app/controllers/GenreController.ts
  src/app/controllers/HealthzController.ts
  src/app/controllers/MovieController.ts
  src/app/models/Actor.ts
  src/app/models/Movie.ts
  src/app/models/Validatable.ts
  src/config/config.ts
  src/db/CosmosDBProvider.ts
  src/db/DatabaseProvider.ts
  src/db/__tests__/query.tests.ts
  src/logging/BunyanLogger.ts
  src/logging/LoggingProvider.ts
  src/middleware/EndpointLogger.ts
  src/secrets/KeyVaultProvider.ts
  src/server.ts
  src/swagger-html.ts
  src/telem/AppInsightsProvider.ts
  src/telem/TelemProvider.ts
  src/utilities/queryUtilities.ts
  tslint.json
Labels: Node

#102 Add param validation and fix movie query bug
  package-lock.json
  package.json
  src/app/controllers/ActorController.ts
  src/app/controllers/MovieController.ts
  src/app/models/Actor.ts
  src/app/models/Movie.ts
  src/app/models/Validatable.ts
  src/config/constants.ts
  src/db/CosmosDBProvider.ts
  src/db/__tests__/query.tests.ts
  src/utilities/__tests__/utils.tests.ts
  src/utilities/validationUtilities.ts
Labels: Node

#103 Remove gulp and rely on a simple npm script
  gulpfile.js
  package.json
Labels: Node

#106 Implement various TypeScript conventions and patterns across the codebase
  src/app/controllers/ActorController.ts
  src/app/controllers/FeaturedController.ts
  src/app/controllers/GenreController.ts
  src/app/controllers/HealthzController.ts
  src/app/controllers/MovieController.ts
  src/app/controllers/index.ts
  src/app/models/index.ts
  src/config/config.ts
  src/db/CosmosDBProvider.ts
  src/logging/BunyanLogger.ts
  src/logging/LoggingProvider.ts
  src/middleware/EndpointLogger.ts
  src/secrets/KeyVaultProvider.ts
  src/server.ts
Labels: Node

#108 Update query result order behavior
  src/app/controllers/FeaturedController.ts
  src/db/CosmosDBProvider.ts
  src/db/__tests__/query.tests.ts
Labels: Node

#104 speed up build and replace script files
  .dockerignore
  Dockerfile
  scripts/run-unit-tests.sh
  scripts/start-service.sh
Labels: Node

#109 change directory structure and service names
  src/config/config.ts
  src/controllers/ActorController.ts
  src/controllers/FeaturedController.ts
  src/controllers/GenreController.ts
  src/controllers/HealthzController.ts
  src/controllers/MovieController.ts
  src/controllers/index.ts
  src/middleware/EndpointLogger.ts
  src/models/Actor.ts
  src/models/Movie.ts
  src/models/index.ts
  src/server.ts
  src/services/AppInsightsService.ts
  src/services/BunyanLogService.ts
  src/services/CosmosDBService.tests.ts
  src/services/CosmosDBService.ts
  src/services/DataService.ts
  src/services/KeyVaultService.ts
  src/services/LogService.ts
  src/services/TelemetryService.ts
Labels: Node

#105 Implement 'object ready' pattern in KeyVaultProvider and CosmosDBProvider
  package.json
  src/config/config.ts
  src/server.ts
  src/services/CosmosDBService.ts
  src/services/DataService.ts
  src/services/KeyVaultService.ts
Labels: Node

#115 Updated order by
  src/services/CosmosDBService.tests.ts
  src/services/CosmosDBService.ts
Labels: Node

#117 Add support for AKS Pod Identity
  package-lock.json
  package.json
  src/services/KeyVaultService.ts
Labels: Node

#122 Remove swagger comments, update IETF, fix 404 error message, initial error handling clean up
  src/controllers/ActorController.ts
  src/controllers/FeaturedController.ts
  src/controllers/GenreController.ts
  src/controllers/HealthzController.ts
  src/controllers/MovieController.ts
  src/models/Actor.ts
  src/models/Movie.ts
  src/server.ts
  src/services/CosmosDBService.ts
Labels: Node

#124 Upgraded test suites and test coverage
  .gitignore
  .mocharc.json
  .nycrc.json
  .vscode/launch.json
  .vscode/tasks.json
  Dockerfile
  Dockerfile-Dev
  README.md
  jest.config.js
  package-lock.json
  package.json
  src/HeliumServer.ts
  src/config/constants.ts
  src/controllers/ActorController.ts
  src/server.ts
  src/services/AppInsightsService.ts
  src/services/BunyanLogService.ts
  src/services/ConsoleLogService.ts
  src/services/CosmosDBService.tests.ts
  src/services/CosmosDBService.ts
  src/services/JsonDataService.ts
  src/services/LogService.ts
  src/services/index.ts
  src/utilities/__tests__/utils.tests.ts
  src/utilities/commandLineUtilities.ts
  src/utilities/dateUtilities.ts
  src/utilities/index.ts
  src/utilities/versionUtilities.ts
  test/e2e/webv.tests.ts
  test/unit/CosmosDBService.tests.ts
  test/unit/utilities.tests.ts
  tsconfig.json
Labels: Node

#129 Fixing Application Insights bug
  src/HeliumServer.ts
  src/server.ts
  src/services/AppInsightsService.ts
Labels: Node

#127 Conform all app comments
  package-lock.json
  package.json
  src/config/config.ts
  src/controllers/ActorController.ts
  src/controllers/FeaturedController.ts
  src/controllers/GenreController.ts
  src/controllers/HealthzController.ts
  src/controllers/MovieController.ts
  src/middleware/EndpointLogger.ts
  src/server.ts
  src/services/AppInsightsService.ts
  src/services/CosmosDBService.ts
  src/services/JsonDataService.ts
  src/services/KeyVaultService.ts
  src/services/LogService.ts
  src/utilities/commandLineUtilities.ts
  src/utilities/dateUtilities.ts
  src/utilities/queryUtilities.ts
  src/utilities/validationUtilities.ts
  src/utilities/versionUtilities.ts
  test/e2e/webv.tests.ts
Labels: Node

#130 Remove HE_ from env vars
  README.md
  src/utilities/commandLineUtilities.ts
Labels: Node

#131 Module for http status checking
  src/controllers/ActorController.ts
  src/controllers/FeaturedController.ts
  src/controllers/GenreController.ts
  src/controllers/MovieController.ts
  src/utilities/httpStatusUtilities.ts
  src/utilities/index.ts
  test/unit/utilities.tests.ts
Labels: Node, Pri1, size: S
