Repository retaildevcrews/helium-typescript, pull requests merged in 2020-02, with the labels that each got.

#62 Typescript - Update designreview.md
  .github/ISSUE_TEMPLATE/designreview.md
Labels: Bug, Documentation, Pri1

#71 update dockerCI.yml and dockerByPr.yml for helium docker build CI
  .github/workflows/dockerByPR.yml
  .github/workflows/dockerCI.old
  .github/workflows/dockerCI.yaml
  README.md
Labels: Enhancement, Pri1, size: S

#72 Update dockerByPR.yml
  .github/workflows/dockerByPR.yml
  .github/workflows/dockerCI.yaml
  package.json
Labels: Bug, Node, Pri1, size: S

#73 Updated Standard Templates (Bug, Task, Release, DoD, Feature)
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/checkpoint.md
  .github/ISSUE_TEMPLATE/designreview.md
  .github/ISSUE_TEMPLATE/dod-review.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/release.md
  .github/ISSUE_TEMPLATE/task.md
Labels: Documentation, Node, Pri1

#74 update ignore paths to ignore all changes to .md files instead of README
  .github/workflows/dockerByPR.yml
  .github/workflows/dockerCI.yaml
Labels: Bug, Node, Pri1, size: S
