Repository retaildevcrews/helium-typescript, pull requests merged in 2020-04, with the labels that each got.

#133 Finish conforming code comments
  src/controllers/HealthzController.ts
  src/controllers/MovieController.ts
  src/services/AppInsightsService.ts
  src/services/BunyanLogService.ts
  src/services/CosmosDBService.ts
  src/services/DataService.ts
  src/services/JsonDataService.ts
  src/services/KeyVaultService.ts
  src/services/TelemetryService.ts
  src/services/index.ts
  src/swagger-html.ts
  src/utilities/commandLineUtilities.ts
  test/unit/utilities.tests.ts
Labels: Node

#135 Replace ready member variables with connect method
  package-lock.json
  src/HeliumServer.ts
  src/config/config.ts
  src/controllers/HealthzController.ts
  src/server.ts
  src/services/CosmosDBService.ts
  src/services/DataService.ts
  src/services/KeyVaultService.ts
  src/utilities/validationUtilities.ts
  test/unit/utilities.tests.ts
Labels: Node

#134 fix linting
  .eslintrc.json
  package.json
Labels: Node

#138 Resolve "expected" HTTP 400 dependency failures in App Insights
  src/services/CosmosDBService.ts
Labels: Node

#139 Refactor the CLI to implement dry run and good usage report
  .eslintrc.json
  README.md
  package.json
  src/HeliumServer.ts
  src/config/ConfigValues.ts
  src/config/ConsoleController.ts
  src/config/cli-config.ts
  src/config/config.ts
  src/config/constants.ts
  src/server.ts
  src/services/AppInsightsService.ts
  src/services/CosmosDBService.ts
  src/services/KeyVaultService.ts
  src/utilities/commandLineUtilities.ts
  src/utilities/index.ts
  src/utilities/versionUtilities.ts
  test/e2e/webv.tests.ts
  test/unit/utilities.tests.ts
Labels: Node

#145 Fix cli default bug and update tests
  src/config/ConsoleController.ts
  src/config/cli-config.ts
  src/controllers/ActorController.ts
  src/controllers/FeaturedController.ts
  src/controllers/GenreController.ts
  src/controllers/HealthzController.ts
  src/controllers/MovieController.ts
  src/services/BunyanLogService.ts
  src/services/ConsoleLogService.ts
  src/services/LogService.ts
  test/e2e/webv.tests.ts
  test/unit/utilities.tests.ts
Labels: Node

#144 Dockerfile and package updates
  Dockerfile
  Dockerfile-Dev
  README.md
  package-lock.json
  package.json
Labels: Node

#148 add workflow for issue triage and PR submitted automation
  .github/workflows/open-issues-triage.yml
  .github/workflows/open-pr-submitted.yml
Labels: Node, Pri1, size: S

#154 Updated Release Template
  .github/ISSUE_TEMPLATE/release.md
Labels: Documentation, Pri1

#153 Cleanup repo for 1.0 release
  README.md
  package-lock.json
  package.json
  src/config/ConsoleController.ts
  src/config/cli-config.ts
  src/controllers/ActorController.ts
  src/controllers/FeaturedController.ts
  src/controllers/GenreController.ts
  src/server.ts
  src/services/AppInsightsService.ts
  src/services/KeyVaultService.ts
  src/utilities/dateUtilities.ts
  src/utilities/queryUtilities.ts
  src/utilities/validationUtilities.ts
  test/e2e/webv.tests.ts
  test/unit/CosmosDBService.tests.ts
  test/unit/utilities.tests.ts
Labels: Node

#155 Remove dockerCI.old workflow
  .github/workflows/dockerCI.old
Labels: Node

#156 Readme title and prereq updates
  README.md
Labels: Node

#157 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation
