Repository retaildevcrews/helium-typescript, pull requests merged in 2020-08, with the labels that each got.

#192 Alfredoch version endpoint
  TestFiles/baseline.json
  src/HeliumServer.ts
  src/config/ConsoleController.ts
  src/config/constants.ts
  src/controllers/HealthzController.ts
  src/utilities/versionUtilities.ts
  test/unit/utilities.tests.ts
Labels: Node, Pri1, good-first-issue, size: S

#193 Renaming MSI references to MI
  README.md
  saveenv.sh
  src/config/ConsoleController.ts
  src/config/cli-config.ts
  src/services/KeyVaultService.ts
  test/unit/utilities.tests.ts
Labels: Node

#194 Updated min and max q param lengths in Swagger UI
  swagger/helium.json
Labels: Bug, Node, Pri1, good-first-issue, size: S

#195 Drain connections + graceful shutdown
  src/HeliumServer.ts
  src/server.ts
Labels: Node

#198 Constant for graceful shutdown timeout
  src/HeliumServer.ts
  src/config/constants.ts
Labels: Node

#200 Move paritionkey to actor/movie models
  src/controllers/ActorController.ts
  src/controllers/FeaturedController.ts
  src/controllers/HealthzController.ts
  src/controllers/MovieController.ts
  src/models/Actor.ts
  src/models/Movie.ts
  src/services/CosmosDBService.ts
  src/services/DataService.ts
  src/utilities/index.ts
  src/utilities/queryUtilities.ts
  test/e2e/webv.tests.ts
  test/unit/utilities.tests.ts
Labels: Node
