Repository retaildevcrews/helium-typescript, pull requests merged in 2020-10, with the labels that each got.

#215 Updated 400 error message content and handling
  TestFiles/bad.json
  TestFiles/e2e.json
  src/config/constants.ts
  src/controllers/ActorController.ts
  src/controllers/MovieController.ts
  src/utilities/apiValidationUtilities.ts
  src/utilities/index.ts
  src/utilities/parameterValidationUtilities.ts
  src/utilities/validationUtilities.ts
  test/unit/utilities.tests.ts
Labels: Enhancement, Pri1, Release

#220 Update deprecated set-env commands for actions to new syntax
  .github/workflows/dockerCI.yaml
Labels: CI/CD

#221 Modifying error response URL headers + changing webv files
  TestFiles/bad.json
  TestFiles/baseline.json
  TestFiles/e2e.json
  src/utilities/apiValidationUtilities.ts
Labels: Node
