Repository retaildevcrews/helium-typescript, pull requests merged in 2020-09, with the labels that each got.

#203 Updated mocha to 8.1.3 to fix serialize-javascript vulnerability
  package-lock.json
  package.json
Labels: Bug

#205 Updated npm packages and fixed issue with uv_signal_start EINVAL
  package-lock.json
  package.json
  src/server.ts
Labels: Bug

#202 Added link check to CI
  .github/ISSUE_TEMPLATE/dod-review.md
  .github/ISSUE_TEMPLATE/user-story.md
  .github/workflows/mdlinkcheck.yml
  README.md
  mlc_config.json
Labels: Bug, Documentation

#207 Added scheduled checks to CI
  .github/ISSUE_TEMPLATE/found-dead-links.md
  .github/workflows/mdlinkcheck.yml
  .github/workflows/scheduled_mdlinkcheck.yml
Labels: Bug, Documentation

#209 Remove proxy comments from dockerfile
  Dockerfile
Labels: Node

#210 Updating NPM packages
  package-lock.json
  package.json
Labels: Node

#211 added .md files, updated CI to run on closed PR
  .github/ISSUE_TEMPLATE/comparison.md
  .github/ISSUE_TEMPLATE/issue.md
  .github/workflows/dockerCI.yaml
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
Labels: CP Review, Documentation, Release

#213 Updated scheduled link check to create project cards
  .github/workflows/scheduled_mdlinkcheck.yml
Labels: Bug, CI/CD, Documentation

#214 Handle closed/cancel PR CI/CD
  .github/workflows/dockerCI.yaml
Labels: Node
