Repository retaildevcrews/helium-typescript, pull requests merged in 2020-05, with the labels that each got.

#161 Swagger Update
  swagger/swagger.json
Labels: Node

#163 swagger path update
  Dockerfile
  Dockerfile-Dev
  README.md
  src/HeliumServer.ts
  src/swagger-html.ts
  swagger/helium.json
  swagger/swagger.json
Labels: Node, Pri1, size: S

#166 Parameterizing offset and limit in cosmos query spec
  src/config/constants.ts
  src/services/CosmosDBService.ts
Labels: Node

#168 Add caching to healthz result
  package-lock.json
  package.json
  src/controllers/HealthzController.ts
  src/server.ts
  swagger/helium.json
Labels: Node

#169 Update dockerByPR.yml
  .github/workflows/dockerByPR.yml
Labels: Pri1, size: S
